// krueger_tm.dart
// Dart port of GeographicLib::TransverseMercator (C++ → Dart)
//
// Transverse Mercator projection using Krüger's 6th-order series,
// as described and corrected by:
//   C. F. F. Karney, "Transverse Mercator with an accuracy of a few nanometers",
//   J. Geodesy 85(8), 475–485 (2011)
//   https://doi.org/10.1007/s00190-011-0445-3
//   Preprint: https://arxiv.org/abs/1002.1417
//
// ==========================================================================
// Original C++: Copyright (c) Charles Karney (2008-2023)
//   <karney@alum.mit.edu>, MIT/X11 License.
//   https://geographiclib.sourceforge.io/
//
// Dart Port:
//   Copyright (c) 2026 Friedhold Matz <fmatz.com@gmail.com>
//   Ported to Dart in 2026.
// Licence:
//   This Dart port is licensed under the MIT/X11 License (same as original).
// ==========================================================================
//
// Accuracy: ≤ 5 nm (nanometers) within 3 500 km (35°) of the central meridian.
// The Dart `double` (IEEE 754 binary64) matches C++ `double`, so the
// round-off properties are identical to the original.

import 'dart:math' as math;

// ---------------------------------------------------------------------------
// Result records
// ---------------------------------------------------------------------------

/// Result of a TM forward projection.
class TMForwardResult {
  /// Transverse-Mercator easting (no false offset), metres.
  final double x;

  /// Transverse-Mercator northing (no false offset), metres.
  final double y;

  /// Meridian convergence (degrees), clockwise from true north.
  final double gamma;

  /// Scale factor at the point.
  final double k;

  const TMForwardResult(
      {required this.x,
      required this.y,
      required this.gamma,
      required this.k});
}

/// Result of a TM reverse projection.
class TMReverseResult {
  /// Geodetic latitude (degrees), positive north.
  final double lat;

  /// Geodetic longitude (degrees), positive east.
  final double lon;

  /// Meridian convergence (degrees).
  final double gamma;

  /// Scale factor at the point.
  final double k;

  const TMReverseResult(
      {required this.lat,
      required this.lon,
      required this.gamma,
      required this.k});
}

// ---------------------------------------------------------------------------
// Core Transverse Mercator class
// ---------------------------------------------------------------------------

/// Krüger/Karney 6th-order Transverse Mercator projection.
///
/// The constructor accepts custom ellipsoid parameters (default: WGS84) and a
/// central scale factor (default: k0 = 1).  For UTM, use k0 = 0.9996 and
/// apply false easting / northing after calling [forward].
///
/// No false easting or northing is added here; that is the responsibility of
/// the caller (see [KarneyUTMConverter]).
class KruegerTM {
  // ---- Ellipsoid parameters ------------------------------------------------
  /// Equatorial radius (metres).
  final double a;

  /// Flattening of the ellipsoid.
  final double f;

  /// Central scale factor.
  final double k0;

  // ---- Derived constants (computed in the constructor) ----------------------
  late final double _e2;   // eccentricity squared
  late final double _es;   // signed eccentricity  sqrt(|e²|) * sign(f)
  late final double _e2m;  // 1 − e²
  late final double _c;    // sqrt(e2m) · exp(eatanhe(1, es))  (scale at pole)
  late final double _n;    // third flattening n = f / (2 − f)
  late final double _b1;   // scale factor for rectifying sphere
  late final double _a1;   // b1 · a  (meridional arc "radius")

  static const int _ord = 6; // series order (= GEOGRAPHICLIB_TRANSVERSEMERCATOR_ORDER)

  // alp[1..6] and bet[1..6] (index 0 unused)
  final _alp = List<double>.filled(_ord + 1, 0.0);
  final _bet = List<double>.filled(_ord + 1, 0.0);

  // ---- Constructor ---------------------------------------------------------

  /// Creates a TM projector for an ellipsoid with equatorial radius [a] (m),
  /// flattening [f], and central scale factor [k0].
  ///
  /// Default values are WGS84 with no central-scale correction (k0 = 1).
  /// For a UTM-compatible projection use k0 = 0.9996.
  KruegerTM({
    this.a = 6378137.0,
    this.f = 1.0 / 298.257223563,
    this.k0 = 1.0,
  }) {
    _e2 = f * (2.0 - f);
    _es = (f < 0 ? -1.0 : 1.0) * math.sqrt(_e2.abs());
    _e2m = 1.0 - _e2;
    _c = math.sqrt(_e2m) * math.exp(_eatanhe(1.0, _es));
    _n = f / (2.0 - f);

    // ---- b1: scale factor for the rectifying sphere -------------------------
    // b1·(n+1) = polyval(m, b1coeff, n²)  /  b1coeff[m+1]
    // b1coeff (order 6, m=3): {1, 4, 64, 256, 256}
    // Generated by Maxima: tmseries.mac
    const b1coeff = [1.0, 4.0, 64.0, 256.0, 256.0];
    const m = _ord ~/ 2; // = 3
    _b1 = _polyval(m, b1coeff, 0, _n * _n) / (b1coeff[m + 1] * (1.0 + _n));
    _a1 = _b1 * a;

    // ---- α series: Gauss-Schreiber → Gauss-Krüger (forward) ----------------
    // From GeographicLib TransverseMercator.cpp, GEOGRAPHICLIB_TRANSVERSEMERCATOR_ORDER == 6
    const alpcoeff = <double>[
      // alp[1]/n^1, polynomial in n of order 5  (7 coefficients + denominator)
      31564.0, -66675.0, 34440.0, 47250.0, -100800.0, 75600.0, 151200.0,
      // alp[2]/n^2, polynomial in n of order 4
      -1983433.0, 863232.0, 748608.0, -1161216.0, 524160.0, 1935360.0,
      // alp[3]/n^3, polynomial in n of order 3
      670412.0, 406647.0, -533952.0, 184464.0, 725760.0,
      // alp[4]/n^4, polynomial in n of order 2
      6601661.0, -7732800.0, 2230245.0, 7257600.0,
      // alp[5]/n^5, polynomial in n of order 1
      -13675556.0, 3438171.0, 7983360.0,
      // alp[6]/n^6, polynomial in n of order 0
      212378941.0, 319334400.0,
    ];

    // ---- β series: Gauss-Krüger → Gauss-Schreiber (inverse) ----------------
    const betcoeff = <double>[
      // bet[1]/n^1, polynomial in n of order 5
      384796.0, -382725.0, -6720.0, 932400.0, -1612800.0, 1209600.0,
      2419200.0,
      // bet[2]/n^2, polynomial in n of order 4
      -1118711.0, 1695744.0, -1174656.0, 258048.0, 80640.0, 3870720.0,
      // bet[3]/n^3, polynomial in n of order 3
      22276.0, -16929.0, -15984.0, 12852.0, 362880.0,
      // bet[4]/n^4, polynomial in n of order 2
      -830251.0, -158400.0, 197865.0, 7257600.0,
      // bet[5]/n^5, polynomial in n of order 1
      -435388.0, 453717.0, 15966720.0,
      // bet[6]/n^6, polynomial in n of order 0
      20648693.0, 638668800.0,
    ];

    // Compute alp[l] = n^l * polyval(...) / denominator
    int o = 0;
    double d = _n;
    for (int l = 1; l <= _ord; ++l) {
      final int mm = _ord - l;
      _alp[l] =
          d * _polyval(mm, alpcoeff, o, _n) / alpcoeff[o + mm + 1];
      _bet[l] =
          d * _polyval(mm, betcoeff, o, _n) / betcoeff[o + mm + 1];
      o += mm + 2;
      d *= _n;
    }
  }

  // ---- Forward projection --------------------------------------------------

  /// Forward TM projection: geographic (lat, lon) → (x, y) in metres.
  ///
  /// [lon0] is the central meridian (degrees).
  /// [lat], [lon] are geodetic latitude and longitude (degrees).
  ///
  /// No false easting or northing is added.
  TMForwardResult forward(double lon0, double lat, double lon) {
    lat = _latFix(lat);

    // lon relative to central meridian, exact difference
    double dlon = _angDiff(lon0, lon);

    // Signed-zero–aware sign extraction (mirrors signbit in C++)
    final int latsign = lat.isNegative ? -1 : 1;
    final int lonsign = dlon.isNegative ? -1 : 1;
    dlon *= lonsign;
    lat *= latsign;

    // "backside": longitude > 90° from central meridian
    final bool backside = dlon > 90.0;
    if (backside) {
      if (lat == 0.0) {
        // latsign stays -1 so northing will be negative for lat=0 backside
      }
      dlon = 180.0 - dlon;
    }

    // sin/cos of lat and dlon
    final sphi = _sincosd(lat);
    final slam = _sincosd(dlon);

    double xip, etap, gamma, k;

    if (lat != 90.0) {
      // tau = tan(phi), taup = tan(phi') = sinh(psi)
      // at lat=90: sphi.c=0, avoid division; handled in else branch
      final double tau = sphi.s / sphi.c;
      final double taup = _taupf(tau, _es);

      xip = math.atan2(taup, slam.c);
      etap = _asinh(slam.s / _hypot(taup, slam.c));
      // Meridian convergence for Gauss-Schreiber (gamma0)
      gamma = _atan2d(slam.s * taup, slam.c * _hypot(1.0, taup));
      // Scale for Gauss-Schreiber
      k = math.sqrt(_e2m + _e2 * sphi.c * sphi.c) *
          _hypot(1.0, tau) /
          _hypot(taup, slam.c);
    } else {
      // Pole
      xip = math.pi / 2.0;
      etap = 0.0;
      gamma = dlon;
      k = _c;
    }

    // ---- Clenshaw summation: (xip, etap) → (xi, eta) ----------------------
    // Sums alp[j] * sin(2j*zeta') in complex zeta = xip + i*etap
    // a = 2 * cos(2*zeta')
    final double c0 = math.cos(2.0 * xip);
    final double ch0 = _cosh(2.0 * etap);
    final double s0 = math.sin(2.0 * xip);
    final double sh0 = _sinh(2.0 * etap);

    double ar = 2.0 * c0 * ch0; // Re(2*cos(2*zeta'))
    double ai = -2.0 * s0 * sh0; // Im(2*cos(2*zeta'))

    int n = _ord;
    double y0r = (n & 1) != 0 ? _alp[n] : 0.0, y0i = 0.0;
    double z0r = (n & 1) != 0 ? 2.0 * n * _alp[n] : 0.0, z0i = 0.0;
    double y1r = 0.0, y1i = 0.0;
    double z1r = 0.0, z1i = 0.0;
    if ((n & 1) != 0) --n;

    // Two-at-a-time Clenshaw
    while (n > 0) {
      // y1 = a * y0 - y1 + alp[n]
      double tr, ti;
      tr = ar * y0r - ai * y0i - y1r + _alp[n];
      ti = ar * y0i + ai * y0r - y1i;
      y1r = tr; y1i = ti;
      // z1 = a * z0 - z1 + 2n * alp[n]
      tr = ar * z0r - ai * z0i - z1r + 2.0 * n * _alp[n];
      ti = ar * z0i + ai * z0r - z1i;
      z1r = tr; z1i = ti;
      --n;
      // y0 = a * y1 - y0 + alp[n]
      tr = ar * y1r - ai * y1i - y0r + _alp[n];
      ti = ar * y1i + ai * y1r - y0i;
      y0r = tr; y0i = ti;
      // z0 = a * z1 - z0 + 2n * alp[n]
      tr = ar * z1r - ai * z1i - z0r + 2.0 * n * _alp[n];
      ti = ar * z1i + ai * z1r - z0i;
      z0r = tr; z0i = ti;
      --n;
    }

    // a /= 2 → cos(2*zeta')
    ar /= 2.0;
    ai /= 2.0;
    // z1 = 1 - z1 + a * z0  (derivative correction)
    z1r = 1.0 - z1r + ar * z0r - ai * z0i;
    z1i = 0.0 - z1i + ar * z0i + ai * z0r;

    // a = sin(2*zeta')
    ar = s0 * ch0;
    ai = c0 * sh0;

    // y1 = zeta' + a * y0  (the output Gauss-Krüger coordinates)
    final double xiOut = xip + ar * y0r - ai * y0i;
    final double etaOut = etap + ar * y0i + ai * y0r;

    // Fold in convergence and scale corrections
    gamma -= _atan2d(z1i, z1r);
    k *= _b1 * _hypot(z1r, z1i);

    // Apply sign conventions
    final double y = _a1 * k0 * (backside ? math.pi - xiOut : xiOut) * latsign;
    final double x = _a1 * k0 * etaOut * lonsign;
    if (backside) gamma = 180.0 - gamma;
    gamma *= latsign * lonsign;
    gamma = _angNormalize(gamma);
    final double kFinal = k * k0;

    return TMForwardResult(x: x, y: y, gamma: gamma, k: kFinal);
  }

  // ---- Reverse projection --------------------------------------------------

  /// Reverse TM projection: (x, y) in metres → geographic (lat, lon).
  ///
  /// [lon0] is the central meridian (degrees).
  /// No false easting or northing is subtracted here.
  TMReverseResult reverse(double lon0, double x, double y) {
    double xi = y / (_a1 * k0);
    double eta = x / (_a1 * k0);

    final int xisign = xi.isNegative ? -1 : 1;
    final int etasign = eta.isNegative ? -1 : 1;
    xi *= xisign;
    eta *= etasign;

    final bool backside = xi > math.pi / 2.0;
    if (backside) xi = math.pi - xi;

    final double c0 = math.cos(2.0 * xi);
    final double ch0 = _cosh(2.0 * eta);
    final double s0 = math.sin(2.0 * xi);
    final double sh0 = _sinh(2.0 * eta);

    // a = 2 * cos(2*zeta)
    double ar = 2.0 * c0 * ch0;
    double ai = -2.0 * s0 * sh0;

    int n = _ord;
    double y0r = (n & 1) != 0 ? -_bet[n] : 0.0, y0i = 0.0;
    double z0r = (n & 1) != 0 ? -2.0 * n * _bet[n] : 0.0, z0i = 0.0;
    double y1r = 0.0, y1i = 0.0;
    double z1r = 0.0, z1i = 0.0;
    if ((n & 1) != 0) --n;

    while (n > 0) {
      double tr, ti;
      // y1 = a * y0 - y1 - bet[n]
      tr = ar * y0r - ai * y0i - y1r - _bet[n];
      ti = ar * y0i + ai * y0r - y1i;
      y1r = tr; y1i = ti;
      // z1 = a * z0 - z1 - 2n * bet[n]
      tr = ar * z0r - ai * z0i - z1r - 2.0 * n * _bet[n];
      ti = ar * z0i + ai * z0r - z1i;
      z1r = tr; z1i = ti;
      --n;
      // y0 = a * y1 - y0 - bet[n]
      tr = ar * y1r - ai * y1i - y0r - _bet[n];
      ti = ar * y1i + ai * y1r - y0i;
      y0r = tr; y0i = ti;
      // z0 = a * z1 - z0 - 2n * bet[n]
      tr = ar * z1r - ai * z1i - z0r - 2.0 * n * _bet[n];
      ti = ar * z1i + ai * z1r - z0i;
      z0r = tr; z0i = ti;
      --n;
    }

    ar /= 2.0;
    ai /= 2.0;
    z1r = 1.0 - z1r + ar * z0r - ai * z0i;
    z1i = 0.0 - z1i + ar * z0i + ai * z0r;

    // sin(2*zeta)
    ar = s0 * ch0;
    ai = c0 * sh0;

    // (xip, etap) = (xi, eta) + a * y0
    final double xip = xi + ar * y0r - ai * y0i;
    final double etap = eta + ar * y0i + ai * y0r;

    double gamma = _atan2d(z1i, z1r);
    double k = _b1 / _hypot(z1r, z1i);

    final double s = _sinh(etap);
    final double c = math.max(0.0, math.cos(xip)); // cos(π/2) can be negative
    final double r = _hypot(s, c);

    double lat, lon;
    if (r != 0.0) {
      lon = _atan2d(s, c); // longitude (degrees) from central meridian
      final double sxip = math.sin(xip);
      // Newton iteration: recover tau = tan(geodetic lat) from taup = tau'
      final double tau = _tauf(sxip / r, _es, _e2m);
      gamma += _atan2d(sxip * _tanh(etap), c);
      lat = _atand(tau);
      k *= math.sqrt(_e2m + _e2 / (1.0 + tau * tau)) *
          _hypot(1.0, tau) *
          r;
    } else {
      lat = 90.0;
      lon = 0.0;
      k *= _c;
    }

    lat *= xisign;
    if (backside) lon = 180.0 - lon;
    lon *= etasign;
    lon = _angNormalize(lon + lon0);
    if (backside) gamma = 180.0 - gamma;
    gamma *= xisign * etasign;
    gamma = _angNormalize(gamma);
    k *= k0;

    return TMReverseResult(lat: lat, lon: lon, gamma: gamma, k: k);
  }

  // ==========================================================================
  // Private math utilities
  // (Transcribed from Math.hpp / Math.cpp in GeographicLib)
  // ==========================================================================

  // Horner polynomial evaluation:   p[s] * x^N + p[s+1] * x^(N-1) + … + p[s+N]
  static double _polyval(int N, List<double> p, int s, double x) {
    double y = N < 0 ? 0.0 : p[s++];
    while (--N >= 0) y = y * x + p[s++];
    return y;
  }

  // e * atanh(e * x)  for signed eccentricity es
  // For a sphere (es = 0) or oblate spheroid (es > 0):  es * atanh(es * x)
  // For prolate spheroid (es < 0):  es < 0 → return -|es| * atan(-|es| * x) = |es| * atan(|es| * x)
  static double _eatanhe(double x, double es) {
    return es > 0.0 ? es * _atanh(es * x) : -es * math.atan(-es * x);
  }

  /// τ′ = τ·√(1+σ²) − σ·√(1+τ²)  where σ = sinh(e·atanh(e·sin φ))
  /// Converts tau = tan(geodetic lat) → tau' = tan(conformal lat) = sinh(psi)
  static double _taupf(double tau, double es) {
    final double tau1 = _hypot(1.0, tau);
    final double sig = _sinh(_eatanhe(tau / tau1, es));
    return _hypot(1.0, sig) * tau - sig * tau1;
  }

  /// Newton-Raphson inverse of _taupf (5 iterations, converges to ~1e-18).
  /// Converts tau' = sinh(psi) back to tau = tan(geodetic lat).
  static double _tauf(double taup, double es, double e2m) {
    const int numit = 5;
    // sqrt(ε)/100 ≈ 2.2e-10; good enough since convergence is quadratic
    final double tol = math.sqrt(5e-16) / 100.0;
    double tau = taup / e2m; // initial estimate (exact for sphere)
    final double stol = tol * math.max(1.0, taup.abs());
    for (int i = 0; i < numit; ++i) {
      final double taupa = _taupf(tau, es);
      final double dtau = (taup - taupa) *
          (1.0 + e2m * tau * tau) /
          (e2m * _hypot(1.0, tau) * _hypot(1.0, taupa));
      tau += dtau;
      if (dtau.abs() < stol) break;
    }
    return tau;
  }

  static double _latFix(double x) => x.abs() > 90.0 ? double.nan : x;

  /// Exact (y − x) reduced to [−180, 180].
  static double _angDiff(double x, double y) => _angNormalize(y - x);

  /// Angle reduced to [−180, 180].
  static double _angNormalize(double x) {
    x %= 360.0;
    if (x <= -180.0) return x + 360.0;
    if (x > 180.0) return x - 360.0;
    return x;
  }

  // Precise sin/cos in degrees – exact for multiples of 30° and 45°
  static _SC _sincosd(double x) {
    // Reduce to [-45, 45], then use the quadrant for exact special values
    final double d = x % 360.0;
    int q = (d / 90.0).round();
    double r = (d - 90.0 * q) * (math.pi / 180.0);
    double s = math.sin(r), c = math.cos(r);
    switch (q & 3) {
      case 0: break;
      case 1: final tmp = c; c = -s; s = tmp; break;
      case 2: s = -s; c = -c; break;
      case 3: final tmp = -c; c = s; s = tmp; break;
    }
    return _SC(s, c);
  }

  static double _atan2d(double y, double x) =>
      math.atan2(y, x) * (180.0 / math.pi);
  static double _atand(double x) => math.atan(x) * (180.0 / math.pi);

  // Numerically stable helpers (not in dart:math)
  static double _hypot(double x, double y) => math.sqrt(x * x + y * y);
  static double _atanh(double x) {
    if (x.abs() >= 1.0) return x.isNegative ? double.negativeInfinity : double.infinity;
    return 0.5 * math.log((1.0 + x) / (1.0 - x));
  }

  // Numerically stable asinh: avoids catastrophic cancellation in
  // log(x + sqrt(x²+1)) when |x| ≪ 1 (up to 6 bits are lost in naive form).
  // Uses the rationalized form: asinh(x) = log1p(|x| + |x|²/(sqrt(|x|²+1)+1)).
  static double _asinh(double x) {
    final double ax = x.abs();
    if (ax > 1e7) {
      // Asymptotic: asinh(x) ≈ sign(x) * (ln2 + ln|x|)
      return (x < 0 ? -1.0 : 1.0) * (math.ln2 + math.log(ax));
    }
    // Rationalized form: u = ax²/(sqrt(ax²+1)+1) = sqrt(ax²+1)-1
    // So ax + u = sqrt(ax²+1) - 1 + ax  (both summands small → full precision).
    // Then asinh(x) = log(1 + (ax + u)) where (ax+u) is computed first.
    final double u = ax * ax / (math.sqrt(ax * ax + 1.0) + 1.0);
    final double v = ax + u; // both small: preserve full relative precision
    return (x < 0 ? -1.0 : 1.0) * math.log(1.0 + v);
  }
  static double _sinh(double x) {
    final double e = math.exp(x);
    return (e - 1.0 / e) / 2.0;
  }

  static double _cosh(double x) {
    final double e = math.exp(x);
    return (e + 1.0 / e) / 2.0;
  }

  static double _tanh(double x) {
    final double e = math.exp(2.0 * x);
    return (e - 1.0) / (e + 1.0);
  }
}

/// Tiny helper – sin/cos pair returned from [KruegerTM._sincosd].
class _SC {
  final double s, c;
  const _SC(this.s, this.c);
}
